import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Product } from './product.entity';

@Injectable()
export class ProductsService implements OnModuleInit {
  constructor(
    @InjectRepository(Product)
    private readonly productRepository: Repository<Product>,
  ) {}

  async onModuleInit() {
    await this.seedProducts();
  }

  private async seedProducts() {
    // Re-seed if database has fewer than the expected 30 products
    const existingCount = await this.productRepository.count();
    if (existingCount > 0) {
      if (existingCount < 30) {
        console.log('Legacy product count detected. Clearing products for re-seeding...');
        await this.productRepository.clear();
      } else {
        return; // Already seeded with all 30 products
      }
    }

    const mockProducts: Partial<Product>[] = [
      // ==========================================
      // 1. WOMEN'S PRODUCTS (gender: 'women')
      // ==========================================
      
      // ---- Women's Clothes ----
      {
        name: 'Evening Dress',
        brand: 'Dorothy Perkins',
        price: 12.0,
        originalPrice: 15.0,
        discountPercent: 20,
        rating: 5.0,
        ratingCount: 10,
        imageUrl: '/assets/evening_dress_product.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'dresses',
        gender: 'women',
        colors: 'black,red,white',
        sizes: 'S,M,L',
      },
      {
        name: 'Sport Dress',
        brand: 'Sitlly',
        price: 19.0,
        originalPrice: 22.0,
        discountPercent: 15,
        rating: 5.0,
        ratingCount: 10,
        imageUrl: '/assets/sport_dress_product.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'dresses',
        gender: 'women',
        colors: 'black,blue',
        sizes: 'XS,S,M',
      },
      {
        name: 'Denim Jacket',
        brand: 'Mango',
        price: 29.0,
        originalPrice: 45.0,
        discountPercent: 35,
        rating: 4.5,
        ratingCount: 18,
        imageUrl: '/assets/product_denim_jacket.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'outerwear',
        gender: 'women',
        colors: 'blue,grey,black',
        sizes: 'M,L,XL',
      },
      {
        name: 'Wrap Dress',
        brand: 'H&M',
        price: 24.0,
        originalPrice: 38.0,
        discountPercent: 37,
        rating: 4.0,
        ratingCount: 22,
        imageUrl: '/assets/product_wrap_dress.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'dresses',
        gender: 'women',
        colors: 'red,white,tan',
        sizes: 'S,M,L,XL',
      },
      {
        name: 'Striped Top',
        brand: 'Dorothy Perkins',
        price: 15.0,
        rating: 4.5,
        ratingCount: 5,
        imageUrl: '/assets/new_product_1.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'tops',
        gender: 'women',
        colors: 'black,white,red',
        sizes: 'XS,S,M,L',
      },
      {
        name: 'White T-Shirt',
        brand: 'Sitlly',
        price: 12.0,
        rating: 4.0,
        ratingCount: 3,
        imageUrl: '/assets/new_product_2.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'tops',
        gender: 'women',
        colors: 'white,grey',
        sizes: 'S,M,L',
      },
      {
        name: 'Summer Blouse',
        brand: 'Zara',
        price: 22.0,
        rating: 4.5,
        ratingCount: 14,
        imageUrl: '/assets/product_summer_blouse.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'tops',
        gender: 'women',
        colors: 'white,tan,red',
        sizes: 'XS,S,M',
      },
      {
        name: 'Maxi Skirt',
        brand: 'Mango',
        price: 28.0,
        rating: 4.0,
        ratingCount: 8,
        imageUrl: '/assets/product_maxi_skirt.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'skirts',
        gender: 'women',
        colors: 'black,tan,blue',
        sizes: 'S,M,L',
      },
      {
        name: 'Linen Pants',
        brand: 'H&M',
        price: 32.0,
        rating: 4.5,
        ratingCount: 19,
        imageUrl: '/assets/product_linen_pants.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'pants',
        gender: 'women',
        colors: 'tan,white,grey',
        sizes: 'M,L,XL',
      },
      {
        name: 'Knit Sweater',
        brand: 'Dorothy Perkins',
        price: 26.0,
        rating: 5.0,
        ratingCount: 12,
        imageUrl: '/assets/product_knit_sweater.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'sweaters',
        gender: 'women',
        colors: 'grey,black,red',
        sizes: 'S,M,L,XL',
      },
      {
        name: 'Skinny Fit Jeans',
        brand: 'Zara',
        price: 34.0,
        originalPrice: 45.0,
        discountPercent: 24,
        rating: 4.2,
        ratingCount: 9,
        imageUrl: '/assets/cat_jeanswear.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'jeans',
        gender: 'women',
        colors: 'blue,black',
        sizes: 'S,M,L,XL',
      },

      // ---- Women's Shoes ----
      {
        name: 'Platform Sneakers',
        brand: 'Nike',
        price: 59.0,
        originalPrice: 89.0,
        discountPercent: 34,
        rating: 5.0,
        ratingCount: 45,
        imageUrl: '/assets/product_sneakers.png',
        isNew: false,
        isSale: true,
        category: 'shoes',
        subcategory: 'sneakers',
        gender: 'women',
        colors: 'white,black,blue',
        sizes: 'S,M,L',
      },
      {
        name: 'Casual Sandals',
        brand: 'Zara',
        price: 24.0,
        rating: 4.4,
        ratingCount: 11,
        imageUrl: '/assets/cat_accessories_hats.png',
        isNew: true,
        isSale: false,
        category: 'shoes',
        subcategory: 'sandals',
        gender: 'women',
        colors: 'tan,white',
        sizes: 'S,M,L',
      },
      {
        name: 'Red Stiletto Heels',
        brand: 'Dorothy Perkins',
        price: 45.0,
        originalPrice: 55.0,
        discountPercent: 18,
        rating: 4.8,
        ratingCount: 15,
        imageUrl: '/assets/cat_partywear.png',
        isNew: false,
        isSale: true,
        category: 'shoes',
        subcategory: 'heels',
        gender: 'women',
        colors: 'red,black',
        sizes: 'S,M,L',
      },
      {
        name: 'Warm Leather Boots',
        brand: 'Mango',
        price: 89.0,
        rating: 4.7,
        ratingCount: 20,
        imageUrl: '/assets/cat_beachwear.png',
        isNew: true,
        isSale: false,
        category: 'shoes',
        subcategory: 'boots',
        gender: 'women',
        colors: 'black,tan',
        sizes: 'M,L',
      },

      // ---- Women's Accessories ----
      {
        name: 'Leather Handbag',
        brand: 'Zara',
        price: 35.0,
        originalPrice: 55.0,
        discountPercent: 36,
        rating: 4.5,
        ratingCount: 31,
        imageUrl: '/assets/product_leather_bag.png',
        isNew: false,
        isSale: true,
        category: 'accessories',
        subcategory: 'bags',
        gender: 'women',
        colors: 'black,tan,grey',
        sizes: 'M',
      },
      {
        name: 'Straw Sun Hat',
        brand: 'H&M',
        price: 15.0,
        rating: 4.3,
        ratingCount: 6,
        imageUrl: '/assets/cat_accessories_hats.png',
        isNew: true,
        isSale: false,
        category: 'accessories',
        subcategory: 'hats',
        gender: 'women',
        colors: 'tan,white',
        sizes: 'M',
      },
      {
        name: 'Retro Sunglasses',
        brand: 'Mango',
        price: 29.0,
        rating: 4.6,
        ratingCount: 14,
        imageUrl: '/assets/cat_vintage.png',
        isNew: true,
        isSale: false,
        category: 'accessories',
        subcategory: 'sunglasses',
        gender: 'women',
        colors: 'black,brown',
        sizes: 'M',
      },

      // ==========================================
      // 2. MEN'S PRODUCTS (gender: 'men')
      // ==========================================
      
      // ---- Men's Clothes ----
      {
        name: 'Casual Check Shirt',
        brand: 'Jack & Jones',
        price: 24.0,
        rating: 4.5,
        ratingCount: 16,
        imageUrl: '/assets/cat_officestyle.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'shirts',
        gender: 'men',
        colors: 'blue,white',
        sizes: 'M,L,XL',
      },
      {
        name: 'Premium Red Hoodie',
        brand: 'adidas Originals',
        price: 39.0,
        originalPrice: 49.0,
        discountPercent: 20,
        rating: 4.9,
        ratingCount: 22,
        imageUrl: '/assets/mens_hoodies_banner.png',
        isNew: false,
        isSale: true,
        category: 'clothes',
        subcategory: 'hoodies',
        gender: 'men',
        colors: 'red,black,grey',
        sizes: 'M,L,XL',
      },
      {
        name: 'Classic Cargo Pants',
        brand: 's.Oliver',
        price: 35.0,
        rating: 4.2,
        ratingCount: 8,
        imageUrl: '/assets/cat_cargo.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'pants',
        gender: 'men',
        colors: 'black,grey',
        sizes: 'M,L,XL',
      },
      {
        name: 'Slim Fit Denim Jeans',
        brand: 'Jack & Jones',
        price: 45.0,
        rating: 4.4,
        ratingCount: 19,
        imageUrl: '/assets/cat_jeanswear.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'jeans',
        gender: 'men',
        colors: 'blue,black',
        sizes: 'M,L,XL',
      },
      {
        name: 'Casual Active Shorts',
        brand: 'adidas Originals',
        price: 19.0,
        rating: 4.7,
        ratingCount: 25,
        imageUrl: '/assets/cat_activewear.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'shorts',
        gender: 'men',
        colors: 'black,blue',
        sizes: 'M,L,XL',
      },
      {
        name: 'Sport Running Tee',
        brand: 'adidas Originals',
        price: 15.0,
        rating: 4.6,
        ratingCount: 30,
        imageUrl: '/assets/cat_sportswear.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'tops',
        gender: 'men',
        colors: 'grey,black,blue',
        sizes: 'M,L,XL',
      },

      // ---- Men's Shoes ----
      {
        name: 'Men Canvas Sneakers',
        brand: 'Nike',
        price: 49.0,
        rating: 4.8,
        ratingCount: 40,
        imageUrl: '/assets/product_sneakers.png',
        isNew: true,
        isSale: false,
        category: 'shoes',
        subcategory: 'sneakers',
        gender: 'men',
        colors: 'black,white',
        sizes: 'M,L,XL',
      },

      // ---- Men's Accessories ----
      {
        name: 'Casual Leather Belt',
        brand: 's.Oliver',
        price: 19.0,
        rating: 4.5,
        ratingCount: 12,
        imageUrl: '/assets/cat_loungewear.png',
        isNew: true,
        isSale: false,
        category: 'accessories',
        subcategory: 'belts',
        gender: 'men',
        colors: 'black,tan',
        sizes: 'L',
      },
      {
        name: 'Classic Sport Cap',
        brand: 'adidas Originals',
        price: 12.0,
        rating: 4.3,
        ratingCount: 8,
        imageUrl: '/assets/cat_accessories_hats.png',
        isNew: true,
        isSale: false,
        category: 'accessories',
        subcategory: 'hats',
        gender: 'men',
        colors: 'black,blue',
        sizes: 'L',
      },

      // ==========================================
      // 3. KIDS' PRODUCTS (gender: 'kids')
      // ==========================================
      
      // ---- Kids Clothes & Shoes ----
      {
        name: 'Kids Graphic Tee',
        brand: 'H&M',
        price: 9.0,
        rating: 4.5,
        ratingCount: 6,
        imageUrl: '/assets/new_product_2.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'tops',
        gender: 'kids',
        colors: 'red,blue,white',
        sizes: 'XS,S',
      },
      {
        name: 'Kids Cargo Jeans',
        brand: 'Mango',
        price: 22.0,
        rating: 4.1,
        ratingCount: 4,
        imageUrl: '/assets/cat_jeanswear.png',
        isNew: true,
        isSale: false,
        category: 'clothes',
        subcategory: 'jeans',
        gender: 'kids',
        colors: 'blue',
        sizes: 'XS,S',
      },
      {
        name: 'Kids Running Sneakers',
        brand: 'Nike',
        price: 29.0,
        rating: 4.9,
        ratingCount: 15,
        imageUrl: '/assets/product_sneakers.png',
        isNew: true,
        isSale: false,
        category: 'shoes',
        subcategory: 'sneakers',
        gender: 'kids',
        colors: 'white,red,blue',
        sizes: 'XS,S',
      },
    ];

    await this.productRepository.save(mockProducts);
    console.log('Successfully seeded database with 30 initial products.');
  }

  async getNewProducts(): Promise<Product[]> {
    return this.productRepository.find({ where: { isNew: true } });
  }

  async getSaleProducts(): Promise<Product[]> {
    return this.productRepository.find({ where: { isSale: true } });
  }

  async getAllProducts(): Promise<Product[]> {
    return this.productRepository.find();
  }
}
